const customers = [
    {
        name: "Aditya Mishra",
        email: "Mishra.adi66@gmail.com",
        password: "12345678",
        adhaar_no: 801710483565,
        phone_no: 8716825278,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "satna",
            tehshil: "birsinghpur",
            city: "satna",
            pincode: 485001,
        },
    },

    {
        name: "Aditya Majumdar",
        email: "adimajum45@gmail.com",
        password: "12345678",
        adhaar_no: 582154556445,
        phone_no: 7845961235,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "anuppur",
            tehshil: "rajendra nagar",
            city: "anuppur",
            pincode: 451565,
        },
    },
    {
        name: "Ayushi Kushwaha ",
        email: "ayushii8574@gamil.com",
        password: "12345678",
        adhaar_no: 874596425465,
        phone_no: 8754968574,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "rewa",
            tehshil: "shivpuri",
            city: "rewa",
            pincode: 457845,
        },
    },
    {
        name: "Dhanshri dale",
        email: "daledhanshri984@gmail.com",
        password: "12345678",
        adhaar_no: 875496214563,
        phone_no: 8745123654,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "chhindwara",
            tehshil: "nirwari",
            city: "chhindwara",
            pincode: 458549,
        },
    },
    {
        name: "Dev Tripathi",
        email: "devtripathi54@gmail.com",
        password: "12345678",
        adhaar_no: 874596153545,
        phone_no: 9874586925,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "chitrakoot",
            tehshil: "majgawan",
            city: "satna",
            pincode: 485001,
        },
    },
    {
        name: "Gaurav singh",
        email: "singh.gaurav54@gmail.com",
        password: "12345678",
        adhaar_no: 874596254136,
        phone_no: 7854963258,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "khajrana",
            tehshil: "indore",
            city: "indore",
            pincode: 462156,
        },
    },
    {
        name: "Hemadri jain",
        email: "hema.jain488@gmail.com",
        password: "12345678",
        adhaar_no: 874596544785,
        phone_no: 7854962587,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "vidisha",
            tehshil: "rajwada",
            city: "vidisha",
            pincode: 262058,
        },
    },
    {
        name: "Manas Rajawat",

        email: "manas.raj74@gamil.com",
        password: "12345678",
        adhaar_no: 874596321458,
        phone_no: 6547893254,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "Bhopal",
            tehshil: "misrod",
            city: "bhopal",
            pincode: 462016,
        },
    },
    {
        name: "Manshi Sahu",
        email: "mansi77494@gmail.com",
        password: "12345678",
        adhaar_no: 874596254869,
        phone_no: 6548745216,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "bhopal",
            tehshil: "lalghati",
            city: "bhopal",
            pincode: 462001,
        },
    },
    {
        name: "Kirti Pandey",

        email: "kirtiii758@gmail.com",
        password: "12345678",
        adhaar_no: 745896256341,
        phone_no: 6258741369,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "satna",
            tehshil: "Raghurajnagar",
            city: "satna",
            pincode: 485001,
        },
    },
    {
        name: "Vedant Updhayay",
        email: "vedu143@gmail.com",
        password: "12345678",
        adhaar_no: 874596254136,
        phone_no: 9874589654,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "sagar",
            tehshil: "manda",
            city: "sagar",
            pincode: 457412,
        },
    },
    {
        name: "Ashish singh",
        email: "ashish6666@gmail.com",
        password: "12345678",
        adhaar_no: 874565847554,
        phone_no: 6584715215,
        isCustomer: true,
        isSeller: false,
        address: {
            state: "Madhya Pradesh",
            district: "Sehore",
            tehshil: "sehore",
            city: "sehore",
            pincode: 475965,
        },
    },
];
