const products = [
  {
    id: 1,
    productName: "Everglow Insecticide",
    price: 439,
    type: "ins",
    quantity: "100ML",
    productId: 439,
    sellCount: 64,
    lic: 296315,
    image: "/images/Insecticides/insecticides8.png",
    sellerId:1
  },
  {
    id: 2,
    productName: "Neem Takat Organic Neem Oil Spary",
    price: 200,
    type: "ins",
    quantity: "450ML",
    productId: 908,
    sellCount: 400,
    lic: 784532,
    image: "/images/Insecticides/insecticides2.png",
    sellerId:2
  },
  {
    id: 3,
    productName: "No Ant Liquid Ant Spray",
    price: 199,
    type: "ins",
    quantity: "300GMS",
    productId: 234,
    sellCount: 70,
    lic: 298484,
    image: "/images/Insecticides/insecticides1.png",
    sellerId:3
  },
  {
    id: 4,
    productName: "EMA-5 Insecticide",
    price: 499,
    type: "ins",
    quantity: "100ML",
    productId: 373,
    sellCount: 22,
    lic: 752577,
    image: "/images/Insecticides/insecticides7.png",
    selllerid:4
  },
  {
    id: 5,
    productName: "Nicotox-D Tobacco Dust Powder Insecticide",
    price: 249,
    type: "ins",
    quantity: "900GMS",
    productId: 731,
    sellCount: 25,
    lic: 642689,
    image: "/images/Insecticides/insecticides3.png",
    sellerId:5
  },
  {
    id: 6,
    productName: "Dupoint Pexalon ",
    price: 1000,
    type: "ins",
    quantity: "235ML",
    productId: 231,
    sellCount: 54,
    lic: 746766,
    image: "/images/Insecticides/insecticides4.png",
    sellerId:1
  },
  {
    id: 7,
    productName: "Katyayani Pyrethrum 2% Extract",
    price: 490,
    type: "ins",
    quantity: "1000ML",
    productId: 333,
    sellCount: 4,
    lic: 778456,
    image: "/images/Insecticides/insecticides5.png",
    sellerId:2
  },
  {
    id: 8,
    productName: "Turning Point Neem Oil",
    price: 399,
    type: "ins",
    quantity: "250ML",
    productId: 526,
    sellCount: 20,
    lic: 232516,
    image: "/images/Insecticides/insecticides8.png",
    sellerId:3
  },
  {
    id: 46,
    productName: "Streptocycline",
    price: 550,
    type: "ins",
    quantity: "60gm",
    productId: 622,
    sellCount: 20,
    lic: 644516,
    image: "/images/Insecticides/insecticides9.png",
    sellerId:4
  },
  {
    id:47,
    productName:"Z+ Pride",
    price:799,
    type:"ins",
    quantity: "400gm",
    productId: 623,
    sellCount: 15,
    lic: 634516,
    image:"/images/Insecticides/insecticides10.png",
    sellerId:5
},
{
    id:48,
    productName:"Regain Fipronil 0.3% GFL",
    price:1200,
    type:"ins",
    quantity: "5KG",
    productId: 624,
    sellCount: 22,
    lic: 267716,
    image:"/images/Insecticides/insecticides11.png",
    sellerId:1
},
   {
        id:11,
        productName:"Cap-Zole Fungicide",
        price:399,
        type:"fung",
        quantity: "100G",
        productId: 582,
        sellCount: 66,
        lic: 734509,
        image:"/images/Fungicides/fungicides1.png",
        sellerId:2
    },
    {
        id:12,
        productName:"DS Exzole Tebuconazole 2% DS",
        price:299,
        type:"fung",
        quantity: "100GM",
        productId: 346,
        sellCount: 67,
        lic: 458636,
        image:"/images/Fungicides/fungicides2.png",
        sellerId:3
    },
    {
        id:13,
        productName:"Full Care Tebuconazole 25.9% EC",
        price:399,
        type:"fung",
        quantity: "100ML",
        productId: 547,
        sellCount: 87,
        lic: 634587,
        image:"/images/Fungicides/fungicides3.png",
        sellerId:4
    },
    {
        id:14,
        productName:"Shine Propiconazole 25% EC",
        price:350,
        type:fung,
        quantity: "250ML",
        productId: 345,
        sellCount: 34,
        lic: 754676,
        image:"/images/Fungicides/fungicides4.png",
        sellerId:5
    },
    {
        id:15,
        productName:"Stop Thiphanate Methyl 70% WP",
        price:100,
        type:"fung",
        quantity: "50GM",
        productId: 238,
        sellCount: 87,
        lic: 342312,
        image:"/images/Fungicides/fungicides5.png",
        sellerId:1
    },
    {
        id:16,
        productName:"Sulfovit Sulphur 80% WDG",
        price:499,
        type:"fung",
        quantity: "1KG",
        productId: 545,
        sellCount: 90,
        lic: 398758,
        image:"/images/Fungicides/fungicides6.png",
        sellerId:2
    },
    {
        id:17,
        productName:"Swing Fungicide",
        price:200,
        type:"fung",
        quantity: "200GMS",
        productId: 375,
        sellCount: 56,
        lic: 956897,
        image:"/images/Fungicides/fungicides7.png",
        sellerId:3
    },
    {
        id:18,
        productName:"Glow Plus Hexaconazole 5% SC",
        price:100,
        type:"fung",
        quantity: "1L",
        productId: 988,
        sellCount: 45,
        lic: 876856,
        image:"/images/Fungicides/fungicides8.png",
        sellerId:4
    },
    {
        id:19,
        productName:"Mass M45 2.5% SC",
        price:159,
        type:"fung",
        quantity: "500ML",
        productId: 436,
        sellCount: 87,
        lic: 876567,
        image:"/images/Fungicides/fungicides10.png",
        sellerId:5
    },
    {
        id:20,
        productName:"Lagoon Isoprothiolane 40% EC",
        price:459,
        type:"fung",
        quantity: "250ML",
        productId: 765,
        sellCount: 48,
        lic: 653755,
        image:"/images/Fungicides/fungicides9.png",
        sellerId:1
    },
    {
        id:49,
        productName:"Kronos Fungicide",
        price:350,
        type:"fung",
        quantity: "1L",
        productId: 624,
        sellCount: 29,
        lic: 653489,
        image:"/images/Fungicides/fungicides11.png",
        sellerId:2
    },
    {
        id:50,
        productName:"Phonic Thiophanate Methyl 70% WP",
        price:750,
        type:"fung",
        quantity: "750GM",
        productId: 625,
        sellCount: 34,
        lic: 896755,
        image:"/images/Fungicides/fungicides12.png",
        sellerId:3
    },
    {
        id:51,
        productName:"Trucop Contact Fungicide",
        price:320,
        type:"fung",
        quantity: "500GM",
        productId: 626,
        sellCount: 23,
        lic: 882756,
        image:"/images/Fungicides/fungicides13.png",
        sellerId:4
    },
    {
        id:52,
        productName:"Merger Contact & Systemic Fungicide",
        price:1099,
        type:"fung",
        quantity: "1KG",
        productId: 627,
        sellCount: 99,
        lic: 265985,
        image:"/images/Fungicides/fungicides14.png",
        sellerId:5
    },
    {
        id:53,
        productName:"Safety Fungicide",
        price:499,
        type:"fung",
        quantity: "1KG",
        productId: 628,
        sellCount: 105,
        lic: 653755,
        image:"/images/Fungicides/fungicides15.png",
        sellerId:1
    },
    {
        id:54,
        productName:"Borogold+",
        price:299,
        type:"fung",
        quantity: "250ML",
        productId: 629,
        sellCount: 19,
        lic: 265635,
        image:"/images/Fungicides/fungicides16.png",
        sellerId:2
    },
    {
        id:21,
        productName:"Ankur Hybrid Bringal Seeds",
        price:200,
        type:"Hyb",
        quantity: "",
        productId: 643,
        sellCount: 98,
        lic: 298765,
        image:"/images/HybridSeeds/seed7.png",
        sellerId:3
    },
    {
        id:22,
        productName:"Sakata Cabbage Seeds Hybrid Charmant",
        price:100,
        type:"Hyb",
        quantity: "250GM",
        productId: 989,
        sellCount: 67,
        lic: 145375,
        image:"/images/HybridSeeds/seed2.png",
        sellerId:4
    },
    {
        id:23,
        productName:"Foargen Maize Master Seeds",
        price:300,
        type:"Hyb.",
        quantity: "1KG",
        productId: 13998,
        sellCount: 52,
        lic: 615478,
        image:"/images/HybridSeeds/seed1.png",
        sellerId:5
    },
    {
        id:24,
        productName:"Trustbasket Lemongrass Hybrid Seeds",
        price:218,
        type:"Hyb",
        quantity: "500GM",
        productId: 398,
        sellCount: 12,
        lic: 186432,
        image:"/images/HybridSeeds/seed9.png",
        sellerId:1
    },
    {
        id:25,
        productName:"Farmgokart Hybrid Tomato Seeds",
        price:100,
        type:"Hyb",
        quantity: "1KG",
        productId: 902,
        sellCount: 31,
        lic: 418557,
        image:"/images/HybridSeeds/seed8.png",
        sellerId:2
    },
    {
        id:26,
        productName:"Bioseedveg Hybrid Cauliflower Seeds",
        price:199,
        type:"Hyb",
        quantity: "450GM",
        productId: 122,
        sellCount: 88,
        lic: 309876,
        image:"/images/HybridSeeds/seed6.png",
        sellerId:3
    },
    {
        id:27,
        productName:"Pride Agro Palak Seeds",
        price:20,
        type:"Hyb",
        quantity: "300GM",
        productId: 610,
        sellCount: 90,
        lic: 618408,
        image:"/images/HybridSeeds/seed5.png",
        sellerId:4
    },
    {
        id:28,
        productName:"Bhumiputra Hybrid Bittergaurd Mohini Seeds",
        price:200,
        type:"Hyb",
        quantity: "500GM",
        productId: 310,
        sellCount: 35,
        lic: 106437,
        image:"/images/HybridSeeds/seed4.png",
        sellerId:5
    },
    {
        id:29,
        productName:"Verdent Hybrid Hot Pepper Seeds",
        price:199,
        type:"Hyb",
        quantity: "450GM",
        productId: 111,
        sellCount: 44,
        lic: 233459,
        image:"/images/HybridSeeds/seed3.png",
        sellerId:1
    },
    {
        id:30,
        productName:"Gujarat Hybrid Bhindi Seeds",
        price:100,
        type:"Hyb",
        quantity: "300GM",
        productId: 112,
        sellCount: 65,
        lic: 776578,
        image:"/images/HybridSeeds/seed2.png",
        sellerId:2
    },
    {
        id:55,
        productName:"Bhindi Red F1 Hybrid",
        price:900,
        type:"Hyb",
        quantity: "300GM",
        productId: 630,
        sellCount: 45,
        lic: 569578,
        image:"/images/HybridSeeds/seed10.png",
        sellerId:3
    },
    {
        id:56,
        productName:"GS 8090 Gold Hybrid Paddy Seeds",
        price:400,
        type:"Hyb",
        quantity: "3KG",
        productId: 631,
        sellCount: 209,
        lic: 776587,
        image:"/images/HybridSeeds/seed11.png",
        sellerId:4
    },
    {
        id:57,
        productName:"Gaillardia Indo-American Hybrid Seeds",
        price:499,
        type:"Hyb",
        quantity: "1KG",
        productId: 632,
        sellCount: 34,
        lic: 756988,
        image:"/images/HybridSeeds/seed12.png",
        sellerId:5
    },
    {
        id:58,
        productName:"Cabbage Viswadeep F1 Hybrid",
        price:399,
        type:"Hyb",
        quantity: "300GM",
        productId: 633,
        sellCount: 89,
        lic: 712458,
        image:"/images/HybridSeeds/seed13.png",
        sellerId:1
    },
    {
        id:59,
        productName:"H Sport + BII Cotton Hybrid Seeds",
        price:199,
        type:"Hyb",
        quantity: "750GM",
        productId: 634,
        sellCount: 122,
        lic: 756578,
        image:"/images/HybridSeeds/seed14.png",
        sellerId:2
    },
    {
        id:31,
        productName:"Trust Auxinol Plant Growth Regulator",
        price:599,
        type:"pgr",
        quantity: "50ML",
        productId: 191,
        sellCount: 50,
        lic: 906137,
        image:"/images/PGR/pgr2.png",
        sellerId:3
    },
    {
        id:32,
        productName:"Bio-Tech Taboli Plant Growth",
        price:259,
        type:"pgr",
        quantity: "100ML",
        productId: 910,
        sellCount: 19,
        lic: 101345,
        image:"/images/PGR/pgr3.png",
        sellerId:4
    },
    {
        id:33,
        productName:"Agricultutural Grade Laher Ethrel",
        price:340,
        type:"pgr",
        quantity: "1L",
        productId: 933,
        sellCount: 84,
        lic: 908092,
        image:"/images/PGR/pgr4.png",
        sellerId:5
    },
    {
        id:34,
        productName:"Cytokinin Plant Growth Regulators",
        price:100,
        type:"pgr",
        quantity: "500ML",
        productId: 230,
        sellCount: 86,
        lic: 456754,
        image:"/images/PGR/pgr5.png",
        sellerId:1
    },
    {
        id:35,
        productName:"Gibberellic Acid 0.001% Growfast",
        price:200,
        type:"pgr",
        quantity: "1L",
        productId: 438,
        sellCount: 94,
        lic: 437376,
        image:"/images/PGR/pgr5.png",
        sellerId:2
    },
    {
        id:60,
        productName:"Plantomic",
        price:600,
        type:"pgr",
        quantity: "1L",
        productId: 633,
        sellCount: 50,
        lic: 489676,
        image:"/images/PGR/pgr6.png",
        sellerId:3
    },
    {
        id:61,
        productName:"LAyeRS-PGR",
        price:190,
        type:"pgr",
        quantity: "1L",
        productId: 634,
        sellCount: 129,
        lic: 235689,
        image:"/images/PGR/pgr7.png",
        sellerId:4
    },
    {
        id:62,
        productName:"Sriculan PGR Tricontanol 0.05% EC",
        price:599,
        type:"pgr",
        quantity: "100ML",
        productId: 635,
        sellCount: 88,
        lic: 236546,
        image:"/images/PGR/pgr8.png",
        sellerId:5
    },
    {
        id:63,
        productName:"Bumper Tricontanol 0.1% EW",
        price:899,
        type:"pgr",
        quantity: "1L",
        productId: 635,
        sellCount: 56,
        lic: 489564,
        image:"/images/PGR/pgr9.png",
        sellerId:1
    },
    {
        id:64,
        productName:"Reshot Super Bloom Fresh",
        price:699,
        type:"pgr",
        quantity: "1L",
        productId: 636,
        sellCount: 89,
        lic: 426545,
        image:"/images/PGR/pgr10.png",
        sellerId:2
    },
    {
        id:65,
        productName:"Magic Super Tricontanol 0.1% EW",
        price:499,
        type:"pgr",
        quantity: "1L",
        productId: 637,
        sellCount: 87,
        lic: 875421,
        image:"/images/PGR/pgr11.png",
        sellerId:3
    },
    {
        id:66,
        productName:"Tricontanol 0.05% EC",
        price:799,
        type:"pgr",
        quantity: "1L",
        productId: 638,
        sellCount: 27,
        lic: 858921,
        image:"/images/PGR/pgr12.png",
        sellerId:4
    },
    {
        id:67,
        productName:"Miraculan 0.05% EC",
        price:250,
        type:"pgr",
        quantity: "1L",
        productId: 639,
        sellCount: 190,
        lic: 265471,
        image:"/images/PGR/pgr13.png",
        sellerId:5
    },
    {
        id:68,
        productName:"SLAVES Wealth Techno",
        price:288,
        type:"pgr",
        quantity: "500ML",
        productId: 640,
        sellCount: 17,
        lic: 124578,
        image:"/images/PGR/pgr14.png",
        sellerId:1
    },
    {
        id:69,
        productName:"Chlormequat Chloride 50% SL",
        price:899,
        type:"pgr",
        quantity: "1000ML",
        productId: 641,
        sellCount: 87,
        lic: 236598,
        image:"/images/PGR/pgr15.png",
        sellerId:2
    },
    {
        id:70,
        productName:"Chetak Plant Harmones",
        price:149,
        type:"pgr",
        quantity: "750ML",
        productId: 642,
        sellCount: 89,
        lic: 895674,
        image:"/images/PGR/pgr16.png",
        sellerId:3
    },
    {
        id:71,
        productName:"GreenFert Tricontanol Ew 0.1% MIN",
        price:599,
        type:"pgr",
        quantity: "500ML",
        productId: 643,
        sellCount: 34,
        lic: 567429,
        image:"/images/PGR/pgr17.png",
        sellerId:4
    },
    {
        id:72,
        productName:"DENTRAX Forchlorfenuron (CPPU) 0.1% Liquid",
        price:287,
        type:"pgr",
        quantity: "500ML",
        productId: 644,
        sellCount: 77,
        lic: 458721,
        image:"/images/PGR/pgr18.png",
        sellerId:5
    },
    {
        id:73,
        productName:"Gibberasil-PGR",
        price:890,
        type:"pgr",
        quantity: "1L",
        productId: 645,
        sellCount: 97,
        lic: 8965742,
        image:"/images/PGR/pgr19.png",
        sellerId:1
    },
    {
        id:36,
        productName:"M.O.P Muriate Of Potash 60% K20",
        price:85,
        type:"fer",
        quantity: "399",
        productId: 474,
        sellCount: 46,
        lic: 964767,
        image:"/images/Fertilizers/fertilizer1.png",
        sellerId:2
    },
    {
        id:37,
        productName:"Power Boon Nitro Benzene 35%",
        price:400,
        type:"fer",
        quantity: "2KG",
        productId: 948,
        sellCount: 69,
        lic: 974786,
        image:"/images/Fertilizers/fertilizer2.png",
        sellerId:3
    },
    {
        id:38,
        productName:"Unicorp Biochem Organic Fertilizer",
        price:500,
        type:"fer",
        quantity: "5KG",
        productId: 937,
        sellCount: 38,
        lic: 957966,
        image:"/images/Fertilizers/fertilizer3.png",
        sellerId:4
    },
    {
        id:39,
        productName:"Emerald Green Lawn Fertilizer",
        price:500,
        type:"fer",
        quantity: "10KG",
        productId: 584,
        sellCount: 98,
        lic: 526878,
        image:"/images/Fertilizers/fertilizer4.png",
        sellerId:5
    },
    {
        id:40,
        productName:"Granular Urea Neem Coated 46% Nitrogen",
        price:300,
        type:"fer",
        quantity: "5KG",
        productId: 564,
        sellCount: 46,
        lic: 676489,
        image:"/images/Fertilizers/fertilizer6.png",
        sellerId:1
    },
    {
        id:73,
        productName:"Khirabhco Urea 46% N",
        price:250,
        type:"fer",
        quantity: "5KG",
        productId: 646,
        sellCount: 78,
        lic: 659749,
        image:"/images/Fertilizers/fertilizer7.png",
        sellerId:2
    },
    {
        id:74,
        productName:"Poshan Water Soluble Fertilizer",
        price:700,
        type:"fer",
        quantity: "5KG",
        productId: 647,
        sellCount: 126,
        lic: 852369,
        image:"/images/Fertilizers/fertilizer8.png",
        sellerId:3
    },
    {
        id:75,
        productName:"PM Bharat Urea 46% Nitrogen",
        price:829,
        type:"fer",
        quantity: "5KG",
        productId: 648,
        sellCount: 90,
        lic: 236549,
        image:"/images/Fertilizers/fertilizer9.png",
        sellerId:4
    },
    {
        id:76,
        productName:"G.K.F.C Mega Salf",
        price:1299,
        type:"fer",
        quantity: "5KG",
        productId: 649,
        sellCount: 86,
        lic: 125489,
        image:"/images/Fertilizers/fertilizer10.png",
        sellerId:5
    },
    {
        id:77,
        productName:"Sarson Cake Organic Fertilizer",
        price:1099,
        type:"fer",
        quantity: "1KG",
        productId: 650,
        sellCount: 89,
        lic: 236589,
        image:"/images/Fertilizers/fertilizer11.png",
        sellerId:1
    },
    {
        id:78,
        productName:"Acrona 16:16:16",
        price:490,
        type:"fer",
        quantity: "5KG",
        productId: 651,
        sellCount: "270",
        lic: 258147,
        image:"/images/Fertilizers/fertilizer12.png",
        sellerId:2
    },
    {
        id:79,
        productName:"Grosur Innovative Nutrients",
        price:1099,
        type:"fer",
        quantity: "5KG",
        productId: 652,
        sellCount: "120",
        lic: 676489,
        image:"/images/Fertilizers/fertilizer13.png",
        sellerId:3
    },
    {
        id:80,
        productName:"Shriram 13:00:45",
        price:590,
        type:"fer",
        quantity: "1KG",
        productId: 653,
        sellCount: 190,
        lic: 676489,
        image:"/images/Fertilizers/fertilizer14.png",
        sellerId:4
    },
    {
        id:81,
        productName:"N.P.K Carrier Based Consortia",
        price:279,
        type:"fer",
        quantity: "1KG",
        productId: 654,
        sellCount: 127,
        lic: 236589,
        image:"/images/Fertilizers/fertilizer15.png",
        sellerId:5
    },
    {
        id:82,
        productName:"Trust Basket Coconut Plant Fertilizer",
        price:900,
        type:"fer",
        quantity: "450MG",
        productId: 655,
        sellCount: 143,
        lic: 236929,
        image:"/images/Fertilizers/fertilizer16.png",
        sellerId:1
    },
    {
        id:83,
        productName:"Sikko Brand Ammonium Sulphate 21%N 23%S",
        price:700,
        type:"fer",
        quantity: "50KG",
        productId: 656,
        sellCount: 54,
        lic: 676489,
        image:"/images/Fertilizers/fertilizer17.png",
        sellerId:2
    },
    {
        id:84,
        productName:"Chelate Trace Element Fertilizer",
        price:399,
        type:"fer",
        quantity: "25KG",
        productId: 657,
        sellCount: 120,
        lic: 125479,
        image:"/images/Fertilizers/fertilizer18.png",
        sellerId:3
    },
    {
        id:41,
        productName:"Saathi Herbicide",
        price:300,
        type:"herb",
        quantity: "80G",
        productId: 445,
        sellCount: 100,
        lic: 634590,
        image:"/images/Herbicides/herbicide3.png",
        sellerId:4
    },
    {
        id:42,
        productName:"Hauris Tembotione 34.4% SC ",
        price: 50,
        type:"herb",
        quantity: "500GM",
        productId: 456,
        sellCount: "30",
        lic: 986134,
        image:"/images/Herbicides/herbicide4.png",
        sellerId:5
    },
    {
        id:43,
        productName:"FMC Austral Herbicide",
        price:100,
        type:"herb",
        quantity: "1KG",
        productId: 810,
        sellCount: 68,
        lic: 379145,
        image:"/images/Herbicides/herbicide1.png",
        sellerId:1
    },
    {
        id:44,
        productName:"Imax Metribuzin 70% WP",
        price:50,
        type:"herb",
        quantity: "100G",
        productId: 456,
        sellCount: 77,
        lic: 745098,
        image:"/images/Herbicides/herbicide5.png",
        sellerId:2
    },
    {
        id:45,
        productName:"PRETICAP 37% EW",
        price:100,
        type:"herb",
        quantity: "100ML",
        productId: 755,
        sellCount: 200,
        lic: 671567,
        image:"/images/Herbicides/herbicide2.png",
        sellerId:3
    },
    {
        id:9,
        productName:"Metzin Metribuzin 70% WP",
        price:1590,
        type:"herb",
        quantity: "1KG",
        productId: 625,
        sellCount: "100",
        lic: 329078,
        image:"/images/Herbicides/herbicide1.png",
        sellerId:4
    },
    {
        id:85,
        productName:"Biuron Herbicide",
        price:190,
        type:"herb",
        quantity: "1KG",
        productId: 657,
        sellCount: 157,
        lic: 236658,
        image:"/images/Herbicides/herbicide6.png",
        sellerId:5
    },
    {
        id:86,
        productName:"Glymer-71 Systemic Herbicide",
        price:1590,
        type:"herb",
        quantity: "100Gm",
        productId: 656,
        sellCount: 123,
        lic: 1236545,
        image:"/images/Herbicides/herbicide7.png",
        sellerId:1
    },
    {
        id:87,
        productName:"Selector Herbicide",
        price:170,
        type:"herb",
        quantity: "1KG",
        productId: 657,
        sellCount: 90,
        lic: 329078,
        image:"/images/Herbicides/herbicide8.png",
        sellerId:2
    },
    {
        id:88,
        productName:"Metrizin Metribuzin 70% WP",
        price:300,
        type:"herb",
        quantity: "1KG",
        productId: 658,
        sellCount: 128,
        lic: 789654,
        image:"/images/Herbicides/herbicide9.png",
        sellerId:3
    },
    {
        id:89,
        productName:"Diggaj Herbicide",
        price:290,
        type:"herb",
        quantity: "1KG",
        productId: 659,
        sellCount: 145,
        lic: 123678,
        image:"/images/Herbicides/herbicide10.png",
        sellerId:4
    },
    {
        id:90,
        productName:"LGY-71 Systemic Hebricide",
        price:159,
        type:"herb",
        quantity: "1KG",
        productId: 660,
        sellCount: "167",
        lic: 569832,
        image:"/images/Herbicides/herbicide11.png",
        sellerId:5
    },
    {
        id:91,
        productName:"Farmaan Systemic Herbicide",
        price:250,
        type:"herb",
        quantity: "1KG",
        productId: 661,
        sellCount: 189,
        lic: 329078,
        image:"/images/Herbicides/herbicide12.png",
        sellerId:1
    },
    {
        id:92,
        productName:"Zero-Weed Selective Herbicide",
        price:770,
        type:"herb",
        quantity: "1KG",
        productId: 662,
        sellCount: 78,
        lic: 258963,
        image:"/images/Herbicides/herbicide13.png",
        sellerId:2
    },
    {
        id:93,
        productName:"Metrigle Systemic Herbicide ",
        price:1300,
        type:"herb",
        quantity: "500GM",
        productId: 663,
        sellCount: 145,
        lic: 329078,
        image:"/images/Herbicides/herbicide14.png",
        sellerId:3
    },
    {
        id:94,
        productName:"Butachlor Ready Mix",
        price:190,
        type:"herb",
        quantity: "1L",
        productId: 664,
        sellCount: 90,
        lic: 256428,
        image:"/images/Herbicides/herbicide15.png",
        sellerId:4
    },
    {
        id:95,
        productName:"Tohfa Atrazine 50% WP",
        price:290,
        type:"herb",
        quantity: "1KG",
        productId: 665,
        sellCount: 189,
        lic: 265983,
        image:"/images/Herbicides/herbicide16.png",
        sellerId:5
    },
    {
        id:96,
        productName:"Glyox -71 Glyphosat 71% SG",
        price:799,
        type:"herb",
        quantity: "500GM",
        productId: 666,
        sellCount: 179,
        lic: 329563,
        image:"/images/Herbicides/herbicide17.png",
        sellerId:1
    },
];