const sellers = [
    {
        name: "Anshuman Tripathi",
        licence_no: "LCFD100450",
        email: "anshumantripathi920@gmail.com",
        password: "12345678",
        adhaar_no: "685151135904",
        phone_no: 7869599945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "madhya pradesh",
            district: "satna",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 485334,
        },
    },
    {
        name: "Madhav Tripathi",
        licence_no: "LCFD100451",
        email: "amt12anshu@gmail.com",
        password: "12345678",
        adhaar_no: "987851135905",
        phone_no: 9651690772,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "madhya pradesh",
            district: "satna",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 485334,
        },
    },
    {
        name: "vimal pandey",
        licence_no: "LCFD100452",
        email: "vimaltri123@gmail.com",
        password: "12345678",
        adhaar_no: "685151130004",
        phone_no: 9981168711,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "madhya pradesh",
            district: "rewa",
            tahshil: "majhgawa",
            city: "rewa",
            pincode: 485554,
        },
    },
    {
        name: "prashant mishra",
        licence_no: "LCFD100454",
        email: "prashant920@gmail.com",
        password: "12345678",
        adhaar_no: "995151135904",
        phone_no: 9169599945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "uttar pradesh",
            district: "karwi",
            tahshil: "raghurajnagar",
            city: "sitapur",
            pincode: 786834,
        },
    },
    {
        name: "sahshwat pandey",
        licence_no: "ABCG647223",
        email: "shashwatpan990@gmail.com",
        password: "12345678",
        adhaar_no: "515145235904",
        phone_no: 8085409595,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "uttar pradesh",
            district: "karwi",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 285334,
        },
    },
    {
        name: "Shubham mishra",
        licence_no: "LCFD232323",
        email: "Shubham920@gmail.com",
        password: "12345678",
        adhaar_no: "681551135904",
        phone_no: 7869199945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "uttar pradesh pradesh",
            district: "satna",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 485334,
        },
    },
    {
        name: "ved",
        licence_no: "LCFD786899",
        email: "vedvedved10@gmail.com",
        password: "12345678",
        adhaar_no: "685151145904",
        phone_no: 7989599945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "madhya pradesh",
            district: "rewa",
            tahshil: "majhgawa",
            city: "waterrfall",
            pincode: 485388,
        },
    },
    {
        name: "manish kashap",
        licence_no: "CDFA34534",
        email: "manish55@gmail.com",
        password: "12345678",
        adhaar_no: "734151135904",
        phone_no: 9929599945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "pupnjab",
            district: "rajpura",
            tahshil: "rajpura",
            city: "rajpura",
            pincode: 640178,
        },
    },
    {
        name: "anuj raj",
        licence_no: "KKfg2345",
        email: "meanujraj@gmail.com",
        password: "12345678",
        adhaar_no: "686748135904",
        phone_no: 8796549945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "punjab",
            district: "chandigarh",
            tahshil: "rajhurajnagar",
            city: "karolbag",
            pincode: 786845,
        },
    },
    {
        name: "Saurabh Tripathi",
        licence_no: "HKSG675890",
        email: "TRipathisau277@gmail.com",
        password: "12345678",
        adhaar_no: "685151135904",
        phone_no: 9755555534,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "punjab ",
            district: "Chandigarh",
            tahshil: "patiyala",
            city: "chitrakoot",
            pincode: 606166,
        },
    },
    {
        name: "Vikram singh",
        licence_no: "LCFD134580",
        email: "vk123@gmail.com",
        password: "12345678",
        adhaar_no: "975551135904",
        phone_no: 9769599945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "Punjab",
            district: "mohali",
            tahshil: "pilikothi",
            city: "kamta",
            pincode: 506062,
        },
    },
    {
        name: "kundan Raj",
        licence_no: "BHFD100450",
        email: "kundankd02@gmail.com",
        password: "12345678",
        adhaar_no: "685158935904",
        phone_no: 8869599945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "BIhar",
            district: "Sitamarhi",
            tahshil: "Sitamarhi",
            city: "patna",
            pincode: 584334,
        },
    },
    {
        name: "privanshu kumar",
        licence_no: "LBH429906",
        email: "priv345@gmail.com",
        password: "12345678",
        adhaar_no: "685151135904",
        phone_no: 6698799945,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "Kerala",
            district: "kollam",
            tahshil: "ramanagar",
            city: "ramannagar",
            pincode: 876789,
        },
    },
    {
        name: "VIjaya raj",
        licence_no: "MCFD100450",
        email: "vijayraj678@gmail.com",
        password: "12345678",
        adhaar_no: "895151135904",
        phone_no: 9969599455,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "Maharashtra",
            district: "Nasik",
            tahshil: "vijayawada",
            city: "Nasik",
            pincode: 555432,
        },
    },
    {
        name: "Vinay kumar",
        licence_no: "MCF5600450",
        email: "Vijayraj678@gmail.com",
        password: "12345678",
        adhaar_no: "996151135904",
        phone_no: 8975599455,
        isCustomer: false,
        isSeller: true,
        address: {
            state: "Maharashtra",
            district: "Nasik",
            tahshil: "vijayawada",
            city: "Nasik",
            pincode: 555432,
        },
    },
];
