export const users = [
    {
        name: "Aditya Mishra",
        email: "Mishra.adi66@gmail.com",
        password: "12345678",
        adhaar_no: 801710483565,
        phone_no: 8716825278,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "satna",
            tehshil: "birsinghpur",
            city: "satna",
            pincode: 485001,
        },
    },
    {
        name: "Aditya Majumdar",
        email: "adimajum45@gmail.com",
        password: "12345678",
        adhaar_no: 582154556445,
        phone_no: 7845961235,
        isCustomer: false,
        address: {
            state: "Madhya Pradesh",
            district: "anuppur",
            tehshil: "rajendra nagar",
            city: "anuppur",
            pincode: 451565,
        },
    },
    {
        name: "Ayushi Kushwaha ",
        email: "ayushii8574@gamil.com",
        password: "12345678",
        adhaar_no: 874596425465,
        phone_no: 8754968574,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "rewa",
            tehshil: "shivpuri",
            city: "rewa",
            pincode: 457845,
        },
    },
    {
        name: "Dhanshri dale",
        email: "daledhanshri984@gmail.com",
        password: "12345678",
        adhaar_no: 875496214563,
        phone_no: 8745123654,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "chhindwara",
            tehshil: "nirwari",
            city: "chhindwara",
            pincode: 458549,
        },
    },
    {
        name: "Dev Tripathi",
        email: "devtripathi54@gmail.com",
        password: "12345678",
        adhaar_no: 874596153545,
        phone_no: 9874586925,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "chitrakoot",
            tehshil: "majgawan",
            city: "satna",
            pincode: 485001,
        },
    },
    {
        name: "Gaurav singh",
        email: "singh.gaurav54@gmail.com",
        password: "12345678",
        adhaar_no: 874596254136,
        phone_no: 7854963258,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "khajrana",
            tehshil: "indore",
            city: "indore",
            pincode: 462156,
        },
    },
    {
        name: "Hemadri jain",
        email: "hema.jain488@gmail.com",
        password: "12345678",
        adhaar_no: 874596544785,
        phone_no: 7854962587,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "vidisha",
            tehshil: "rajwada",
            city: "vidisha",
            pincode: 262058,
        },
    },
    {
        name: "Manas Rajawat",

        email: "manas.raj74@gamil.com",
        password: "12345678",
        adhaar_no: 874596321458,
        phone_no: 6547893254,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "Bhopal",
            tehshil: "misrod",
            city: "bhopal",
            pincode: 462016,
        },
    },
    {
        name: "Manshi Sahu",
        email: "mansi77494@gmail.com",
        password: "12345678",
        adhaar_no: 874596254869,
        phone_no: 6548745216,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "bhopal",
            tehshil: "lalghati",
            city: "bhopal",
            pincode: 462001,
        },
    },
    {
        name: "Kirti Pandey",

        email: "kirtiii758@gmail.com",
        password: "12345678",
        adhaar_no: 745896256341,
        phone_no: 6258741369,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "satna",
            tehshil: "Raghurajnagar",
            city: "satna",
            pincode: 485001,
        },
    },
    {
        name: "Vedant Updhayay",
        email: "vedu143@gmail.com",
        password: "12345678",
        adhaar_no: 874596254136,
        phone_no: 9874589654,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "sagar",
            tehshil: "manda",
            city: "sagar",
            pincode: 457412,
        },
    },
    {
        name: "Ashish singh",
        email: "ashish6666@gmail.com",
        password: "12345678",
        adhaar_no: 874565847554,
        phone_no: 6584715215,
        isCustomer: true,
        address: {
            state: "Madhya Pradesh",
            district: "Sehore",
            tehshil: "sehore",
            city: "sehore",
            pincode: 475965,
        },
    },
    {
        sellerId: 1,
        name: "Anshuman Tripathi",
        shop_name: "Krishi Upkaran Dukan",
        licence_no: "LCFD100450",
        email: "anshumantripathi920@gmail.com",
        password: "12345678",
        adhaar_no: "685151135904",
        phone_no: 7869599945,
        isCustomer: false,
        address: {
            state: "madhya pradesh",
            district: "satna",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 485334,
        },
    },
    {
        sellerId: 2,
        name: "Madhav Tripathi",
        shop_name: "Khad Aur Khaad Dukaan",
        licence_no: "LCFD100451",
        email: "amt12anshu@gmail.com",
        password: "12345678",
        adhaar_no: "987851135905",
        phone_no: 9651690772,
        isCustomer: false,
        address: {
            state: "madhya pradesh",
            district: "satna",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 485334,
        },
    },
    {
        sellerId: 3,
        name: "vimal pandey",
        shop_name: "Keet-Nashak Dukaan",
        licence_no: "LCFD100452",
        email: "vimaltri123@gmail.com",
        password: "12345678",
        adhaar_no: "685151130004",
        phone_no: 9981168711,
        isCustomer: false,
        address: {
            state: "madhya pradesh",
            district: "rewa",
            tahshil: "majhgawa",
            city: "rewa",
            pincode: 485554,
        },
    },
    {
        sellerId: 4,
        name: "prashant mishra",
        shop_name: "Krishi Yantra Dukaan",
        licence_no: "LCFD100454",
        email: "prashant920@gmail.com",
        password: "12345678",
        adhaar_no: "995151135904",
        phone_no: 9169599945,
        isCustomer: false,
        address: {
            state: "uttar pradesh",
            district: "karwi",
            tahshil: "raghurajnagar",
            city: "sitapur",
            pincode: 786834,
        },
    },
    {
        sellerId: 5,
        name: "sahshwat pandey",
        shop_name: "Krishi Rasayan Dukaan",
        licence_no: "ABCG647223",
        email: "shashwatpan990@gmail.com",
        password: "12345678",
        adhaar_no: "515145235904",
        phone_no: 8085409595,
        isCustomer: false,
        address: {
            state: "uttar pradesh",
            district: "karwi",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 285334,
        },
    },
    {
        name: "Shubham mishra",
        licence_no: "LCFD232323",
        email: "Shubham920@gmail.com",
        password: "12345678",
        adhaar_no: "681551135904",
        phone_no: 7869199945,
        isCustomer: false,
        address: {
            state: "uttar pradesh pradesh",
            district: "satna",
            tahshil: "majhgawa",
            city: "chitrakoot",
            pincode: 485334,
        },
    },
    {
        name: "ved",
        licence_no: "LCFD786899",
        email: "vedvedved10@gmail.com",
        password: "12345678",
        adhaar_no: "685151145904",
        phone_no: 7989599945,
        isCustomer: false,
        address: {
            state: "madhya pradesh",
            district: "rewa",
            tahshil: "majhgawa",
            city: "waterrfall",
            pincode: 485388,
        },
    },
    {
        name: "manish kashap",
        licence_no: "CDFA34534",
        email: "manish55@gmail.com",
        password: "12345678",
        adhaar_no: "734151135904",
        phone_no: 9929599945,
        isCustomer: false,
        address: {
            state: "pupnjab",
            district: "rajpura",
            tahshil: "rajpura",
            city: "rajpura",
            pincode: 640178,
        },
    },
    {
        name: "anuj raj",
        licence_no: "KKfg2345",
        email: "meanujraj@gmail.com",
        password: "12345678",
        adhaar_no: "686748135904",
        phone_no: 8796549945,
        isCustomer: false,
        address: {
            state: "punjab",
            district: "chandigarh",
            tahshil: "rajhurajnagar",
            city: "karolbag",
            pincode: 786845,
        },
    },
    {
        name: "Saurabh Tripathi",
        licence_no: "HKSG675890",
        email: "TRipathisau277@gmail.com",
        password: "12345678",
        adhaar_no: "685151135904",
        phone_no: 9755555534,
        isCustomer: false,
        address: {
            state: "punjab ",
            district: "Chandigarh",
            tahshil: "patiyala",
            city: "chitrakoot",
            pincode: 606166,
        },
    },
    {
        name: "Vikram singh",
        licence_no: "LCFD134580",
        email: "vk123@gmail.com",
        password: "12345678",
        adhaar_no: "975551135904",
        phone_no: 9769599945,
        isCustomer: false,
        address: {
            state: "Punjab",
            district: "mohali",
            tahshil: "pilikothi",
            city: "kamta",
            pincode: 506062,
        },
    },
    {
        name: "kundan Raj",
        licence_no: "BHFD100450",
        email: "kundankd02@gmail.com",
        password: "12345678",
        adhaar_no: "685158935904",
        phone_no: 8869599945,
        isCustomer: false,
        address: {
            state: "BIhar",
            district: "Sitamarhi",
            tahshil: "Sitamarhi",
            city: "patna",
            pincode: 584334,
        },
    },
    {
        name: "privanshu kumar",
        licence_no: "LBH429906",
        email: "priv345@gmail.com",
        password: "12345678",
        adhaar_no: "685151135904",
        phone_no: 6698799945,
        isCustomer: false,
        address: {
            state: "Kerala",
            district: "kollam",
            tahshil: "ramanagar",
            city: "ramannagar",
            pincode: 876789,
        },
    },
    {
        name: "VIjaya raj",
        licence_no: "MCFD100450",
        email: "vijayraj678@gmail.com",
        password: "12345678",
        adhaar_no: "895151135904",
        phone_no: 9969599455,
        isCustomer: false,
        address: {
            state: "Maharashtra",
            district: "Nasik",
            tahshil: "vijayawada",
            city: "Nasik",
            pincode: 555432,
        },
    },
    {
        name: "Vinay kumar",
        licence_no: "MCF5600450",
        email: "Vijayraj678@gmail.com",
        password: "12345678",
        adhaar_no: "996151135904",
        phone_no: 8975599455,
        isCustomer: false,
        address: {
            state: "Maharashtra",
            district: "Nasik",
            tahshil: "vijayawada",
            city: "Nasik",
            pincode: 555432,
        },
    },
];
